name: SetRankPB
version: 1.2
softdepend: [Spout]
main: com.baummann.setrankpb.SetRankPB
commands:
   setrank:
      description: Changes someone's rank.
      usage: /<command> [Player] [Rank]
      aliases: [rank]
permissions:
   setrankpb.rank.<rank>:
      description: Ability to rank to a specific rank.
      default: op
   setrankpb.rankall:
      description: Permission to rank to every rank.
      default: op