name: SetRankPB
version: 1.1
main: com.baummann.setrankpb.SetRankPB
commands:
   setrank:
      description: Changes someone's rank.
      usage: /<command> [Player] [Rank]
      aliases: [rank]
permissions:
   setrankpb.rankall:
      description: Permission to rank to every rank.
      default: op